export const ROLES = {
  BROKER: 'BROKER',
  CLIENT: 'CLIENT',
  SETTLEMENT_AGENT: 'SETTLEMENT_AGENT',
  OBSERVER: 'OBSERVER',
};

export const ACTIONS = {
  CONFIRM: 'Confirm',
  AFFIRM: 'Affirm',
  ALLOCATE: 'Allocate',
  SETTLE: 'Settle',
  TRANSFER: 'Transer',
};

export const CONFIRMED_ALLOCATION_TRADES_STATUS = {
  CONFIRMED: 'CONFIRMED',
  SETTLED: 'SETTLED',
  TRANSFERRED: 'TRANSFERRED',
};

export const BLOCK_TRADE_STATUS = {
  EMPTY: '',
  ALLOCATED: 'ALLOCATED',
};

export const ALLOCATION_TRADE_STATUS = {
  UNAFFIRMED: 'UNAFFIRMED',
  AFFIRMED: 'AFFIRMED',
  CONFIRMED: 'CONFIRMED',
};
