export const BROKER_BLOCKTRADE_COLUMNS = [
  'tradeAndClient',
  // 'tradeNumber',
  // 'client',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'cash',
  // 'currency',
  // 'valueDate',
  'status',
  'action',
];

export const CLIENT_BLOCKTRADE_COLUMNS = [
  'tradeAndBroker',
  // 'tradeNumber',
  // 'broker',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'cash',
  // 'currency',
  // 'valueDate',
  'status',
];

export const SETTLEMENT_AGENT_BLOCKTRADE_COLUMNS = [
  'tradeAndBroker',
  // 'tradeNumber',
  // 'broker',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'cash',
  // 'currency',
  // 'valueDate',
  'status',
  'action',
];

export const BROKER_ALLOCATION_TRADE_COLUMNS = [
  'blockAndAllocationAndClient',
  // 'blockNumber',
  // 'allocationNumber',
  // 'client',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'cash',
  // 'valueDate',
  'status',
  'action',
];

export const CLIENT_ALLOCATION_TRADE_COLUMNS = [
  'blockAndAllocationAndClient',
  // 'blockNumber',
  // 'allocationNumber',
  // 'client',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'cash',
  // 'valueDate',
  'status',
  'action',
];

export const SETTLEMENT_AGENT_ALLOCATION_TRADE_COLUMNS = [
  'tradeAndBrokerAndClient',
  // 'tradeNumber',
  // 'broker',
  // 'client',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'currency',
  // 'cash',
  // 'valueDate',
  'status',
  'action',
];

export const COLLATERAL_AGENT_ALLOCATION_TRADE_COLUMNS = [
  'tradeAndBrokerAndClient',
  // 'tradeNumber',
  // 'broker',
  // 'client',
  'productRelated',
  // 'prodType',
  // 'product',
  'valueRelated',
  // 'quantity',
  // 'price',
  // 'currency',
  // 'cash',
  // 'valueDate',
  'status',
];
